steps:
  # Build chat_with_human (ADK backend)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/event-sponsor-assistant/${_REPO_NAME}/chat-with-human:latest', './chat_with_human']

  # Build services
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/event-sponsor-assistant/${_REPO_NAME}/services:latest', './services']

  # Build frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/event-sponsor-assistant/${_REPO_NAME}/frontend:latest', './frontend']

  # Push chat_with_human
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/event-sponsor-assistant/${_REPO_NAME}/chat-with-human:latest']

  # Push services
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/event-sponsor-assistant/${_REPO_NAME}/services:latest']

  # Push frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/event-sponsor-assistant/${_REPO_NAME}/frontend:latest']

# Deploy services first (chat_with_human depends on it)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'services-backend'
      - '--image=us-central1-docker.pkg.dev/event-sponsor-assistant/${_REPO_NAME}/services:latest'
      - '--project=event-sponsor-assistant'
      - '--region=us-central1'
      - '--port=8001'
      - '--allow-unauthenticated'
      - '--update-secrets=AIRTABLE_API_KEY=AIRTABLE_API_KEY:latest,AIRTABLE_BASE_ID=AIRTABLE_BASE_ID:latest,AIRTABLE_TABLE_ID=AIRTABLE_TABLE_ID:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--update-secrets=/secrets/gmail_token.json=GMAIL_TOKEN:latest'
    id: 'deploy-services'

  # Deploy chat_with_human (connects to services)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICES_URL=$$(gcloud run services describe services-backend --platform managed --project=event-sponsor-assistant --region us-central1 --format 'value(status.url)') && \
        gcloud run deploy adk-backend-service \
          --image=us-central1-docker.pkg.dev/event-sponsor-assistant/${_REPO_NAME}/chat-with-human:latest \
          --project=event-sponsor-assistant \
          --region=us-central1 \
          --port=8000 \
          --allow-unauthenticated \
          --set-env-vars="SERVICES_URL=$$SERVICES_URL" \
          --update-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest
    waitFor: ['deploy-services']
    id: 'deploy-chat'

  # Deploy frontend (connects to chat_with_human)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$$(gcloud run services describe adk-backend-service --platform managed --project=event-sponsor-assistant --region us-central1 --format 'value(status.url)') && \
        gcloud run deploy adk-frontend-service \
          --image=us-central1-docker.pkg.dev/event-sponsor-assistant/${_REPO_NAME}/frontend:latest \
          --project=event-sponsor-assistant \
          --region=us-central1 \
          --allow-unauthenticated \
          --set-env-vars="ADK_SERVER_URL=$$BACKEND_URL"
    waitFor: ['deploy-chat']

images:
  - 'us-central1-docker.pkg.dev/event-sponsor-assistant/${_REPO_NAME}/chat-with-human:latest'
  - 'us-central1-docker.pkg.dev/event-sponsor-assistant/${_REPO_NAME}/services:latest'
  - 'us-central1-docker.pkg.dev/event-sponsor-assistant/${_REPO_NAME}/frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY