steps:
  # Build chat_with_human (ADK backend)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/event-sponsor-assistant/event-sponsor-repo/chat-with-human:latest', './chat_with_human']

  # Build services
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/event-sponsor-assistant/event-sponsor-repo/services:latest', './services']

  # Push chat_with_human
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/event-sponsor-assistant/event-sponsor-repo/chat-with-human:latest']

  # Push services
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/event-sponsor-assistant/event-sponsor-repo/services:latest']

  # Deploy services first
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'services-backend'
      - '--image=us-central1-docker.pkg.dev/event-sponsor-assistant/event-sponsor-repo/services:latest'
      - '--project=event-sponsor-assistant'
      - '--region=us-central1'
      - '--port=8080'
      - '--allow-unauthenticated'
      - '--update-secrets=AIRTABLE_API_KEY=AIRTABLE_API_KEY:latest,AIRTABLE_BASE_ID=AIRTABLE_BASE_ID:latest,AIRTABLE_TABLE_ID=AIRTABLE_TABLE_ID:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,HUBSPOT_CLIENT_ID=HUBSPOT_CLIENT_ID:latest,HUBSPOT_CLIENT_SECRET=HUBSPOT_CLIENT_SECRET:latest'
      - '--update-secrets=/secrets/gmail_token.json=GMAIL_TOKEN:latest'
      - '--timeout=300'
      - '--memory=512Mi'
    id: 'deploy-services'

  # Deploy chat_with_human
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICES_URL=$$(gcloud run services describe services-backend --platform managed --project=event-sponsor-assistant --region us-central1 --format 'value(status.url)') && \
        gcloud run deploy adk-backend-service \
          --image=us-central1-docker.pkg.dev/event-sponsor-assistant/event-sponsor-repo/chat-with-human:latest \
          --project=event-sponsor-assistant \
          --region=us-central1 \
          --port=8000 \
          --allow-unauthenticated \
          --set-env-vars="SERVICES_URL=$$SERVICES_URL" \
          --update-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest,AIRTABLE_API_KEY=AIRTABLE_API_KEY:latest,AIRTABLE_BASE_ID=AIRTABLE_BASE_ID:latest,AIRTABLE_TABLE_ID=AIRTABLE_TABLE_ID:latest
    waitFor: ['deploy-services']
    id: 'deploy-chat'

  # Upload frontend index.html to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-index'
    args:
      - '-h'
      - 'Cache-Control:no-cache, max-age=0'
      - 'cp'
      - 'frontend/index.html'
      - 'gs://event-sponsor-frontend/'
    waitFor: ['deploy-chat']

  # Upload frontend live.html to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-live'
    args:
      - '-h'
      - 'Cache-Control:no-cache, max-age=0'
      - 'cp'
      - 'frontend/live.html'
      - 'gs://event-sponsor-frontend/'
    waitFor: ['upload-index']

  # Set GCS web main page
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'set-web-main'
    args:
      - 'web'
      - 'set'
      - '-m'
      - 'index.html'
      - 'gs://event-sponsor-frontend/'
    waitFor: ['upload-live']

images:
  - 'us-central1-docker.pkg.dev/event-sponsor-assistant/event-sponsor-repo/chat-with-human:latest'
  - 'us-central1-docker.pkg.dev/event-sponsor-assistant/event-sponsor-repo/services:latest'

options:
  logging: CLOUD_LOGGING_ONLY